name: 'notify'
on:
  pull_request:
  push:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      # After vue3 is released, it will be removed
      # - uses: actions/hello-world-javascript-action@master
      #   with:
      #     who-to-greet: HcySunYang
      # Until the vue3 is released, the real test is taken.
      - run: yarn
      - run: yarn notify $GITHUB_REPOSITORY $GITHUB_EVENT_NAME ${{ secrets.TOKEN }}
